version: '3.11.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=d1.settings
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"