# Generated by Django 5.1.3 on 2024-11-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班级名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teacher_images', verbose_name='头像')),
                ('role', models.IntegerField(choices=[(0, '老师'), (1, '学生')], default=0, verbose_name='角色')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, default='app1/default_avatar.jpg', null=True, upload_to='app/', verbose_name='头像')),
                ('status', models.IntegerField(choices=[(0, '就业'), (1, '升学')], default=0, verbose_name='毕业去向')),
                ('study_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='升学院校')),
                ('study_major', models.CharField(blank=True, max_length=100, null=True, verbose_name='升学专业')),
                ('role', models.IntegerField(choices=[(0, '老师'), (1, '学生')], default=1, verbose_name='角色')),
                ('province', models.IntegerField(choices=[(0, '北京市'), (1, '天津市'), (2, '河北省'), (3, '山西省'), (4, '内蒙古自治区'), (5, '辽宁省'), (6, '吉林省'), (7, '黑龙江省'), (8, '上海市'), (9, '江苏省'), (10, '浙江省'), (11, '安徽省'), (12, '福建省'), (13, '江西省'), (14, '山东省'), (15, '河南省'), (16, '湖北省'), (17, '湖南省'), (18, '广东省'), (19, '广西壮族自治区'), (20, '海南省'), (21, '重庆市'), (22, '四川省'), (23, '贵州省'), (24, '云南省'), (25, '西藏自治区'), (26, '陕西省'), (27, '甘肃省'), (28, '青海省'), (29, '宁夏回族自治区'), (30, '新疆维吾尔自治区'), (31, '台湾省'), (32, '香港特别行政区'), (33, '澳门特别行政区')], default=16, verbose_name='意向地区')),
                ('is_read', models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='已未读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.class', verbose_name='所在班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='app.teacher')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name='负责的老师'),
        ),
    ]
