# Generated by Django 5.1.3 on 2024-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_avatar.jpg', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
