# Generated by Django 5.1.3 on 2024-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_teacher_avatar.jpg', null=True, upload_to='avatars/teachers/%Y/%m/', verbose_name='头像'),
        ),
    ]
