# Generated by Django 5.1.3 on 2024-11-22 01:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_avatar.jpg', null=True, upload_to=app.models.get_file_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_teacher_avatar.jpg', null=True, upload_to=app.models.get_file_path, verbose_name='头像'),
        ),
    ]
