# Generated by Django 5.1.3 on 2024-11-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_avatar_alter_teacher_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_read',
            field=models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='通知状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.IntegerField(choices=[(0, '北京市'), (1, '天津市'), (2, '河北省'), (3, '山西省'), (4, '内蒙古自治区'), (5, '辽宁省'), (6, '吉林省'), (7, '黑龙江省'), (8, '上海市'), (9, '江苏省'), (10, '浙江省'), (11, '安徽省'), (12, '福建省'), (13, '江西省'), (14, '山东省'), (15, '河南省'), (16, '湖北省'), (17, '湖南省'), (18, '广东省'), (19, '广西壮族自治区'), (20, '海南省'), (21, '重庆市'), (22, '四川省'), (23, '贵州省'), (24, '云南省'), (25, '西藏自治区'), (26, '陕西省'), (27, '甘肃省'), (28, '青海省'), (29, '宁夏回族自治区'), (30, '新疆维吾尔自治区'), (31, '台湾省'), (32, '香港特别行政区'), (33, '澳门特别行政区')], default=16, help_text='就业学生填写就业意向地区，升学学生填写升学意向地区', verbose_name='意向地区'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_major',
            field=models.CharField(blank=True, help_text='仅升学学生需填写', max_length=100, null=True, verbose_name='升学专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_school',
            field=models.CharField(blank=True, help_text='仅升学学生需填写', max_length=100, null=True, verbose_name='升学院校'),
        ),
    ]
