# Generated by Django 5.1.3 on 2024-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notice_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='read_notices',
            field=models.ManyToManyField(blank=True, related_name='read_by_students', to='app.notice', verbose_name='已读通知'),
        ),
    ]
