# Generated by Django 5.1.3 on 2024-11-27 03:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_province_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_img.png', null=True, upload_to=app.models.get_file_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '就业'), (1, '考研')], null=True, verbose_name='毕业去向'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_img.png', null=True, upload_to=app.models.get_file_path, verbose_name='头像'),
        ),
    ]
