# Generated by Django 5.1.3 on 2024-12-02 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_student_avatar_alter_student_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='学生信息调查问卷', max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('student_no', models.CharField(max_length=20, verbose_name='学号')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('future_plan', models.IntegerField(choices=[(0, '就业'), (1, '升学深造')], verbose_name='毕业去向')),
                ('employment_type', models.IntegerField(blank=True, choices=[(0, '考公'), (1, '考编'), (2, '企业应聘'), (3, '自主创业')], null=True, verbose_name='就业方式')),
                ('city_preference', models.IntegerField(blank=True, choices=[(0, '一线城市(如北京、上海、广州、深圳)'), (1, '二线城市(如杭州、成都、武汉)'), (2, '学校附近'), (3, '家乡')], null=True, verbose_name='就业城市倾向')),
                ('expected_salary', models.IntegerField(blank=True, choices=[(0, '5000元以下'), (1, '5000-10000元'), (2, '10000元以上')], null=True, verbose_name='期望月薪')),
                ('job_market_view', models.IntegerField(blank=True, choices=[(0, '乐观'), (1, '正常'), (2, '就业难'), (3, '不了解')], null=True, verbose_name='就业形势看法')),
                ('study_type', models.IntegerField(blank=True, choices=[(0, '保研(已录取院校)'), (1, '考研(拟报考院校)'), (2, '境外高校(拟申报院校)')], null=True, verbose_name='升学方式')),
                ('target_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='院校名称')),
                ('study_plan_status', models.IntegerField(blank=True, choices=[(0, '已在实施计划'), (1, '有计划未实施'), (2, '未定计划')], null=True, verbose_name='备考计划')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='app.student', verbose_name='学生')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.survey', verbose_name='关联问卷')),
            ],
            options={
                'verbose_name': '问卷回答',
                'verbose_name_plural': '问卷回答',
                'db_table': 'survey_response',
            },
        ),
    ]
