# Generated by Django 5.1.3 on 2024-12-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_survey_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='gender',
        ),
    ]
