# Generated by Django 5.1.3 on 2024-12-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_survey_options_survey_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='app.student', verbose_name='学生'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('student', 'survey')},
        ),
    ]
