# Generated by Django 5.1.3 on 2024-12-09 02:25

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_surveyresponse_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='省份名称')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='省份代码')),
                ('is_municipality', models.BooleanField(default=False, verbose_name='是否直辖市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'province',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_img.png', null=True, upload_to=app.models.get_file_path, verbose_name='头���'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='城市代码')),
                ('level', models.CharField(choices=[('prefecture', '地级市'), ('county', '县级市'), ('district', '市辖区')], default='prefecture', max_length=20, verbose_name='城市级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='app.province', verbose_name='所属省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
                'ordering': ['province__code', 'code'],
                'unique_together': {('province', 'name')},
            },
        ),
    ]
