# Generated by Django 5.1.3 on 2024-12-09 07:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_province_alter_teacher_avatar_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_img.png', null=True, upload_to=app.models.get_file_path, verbose_name='头像'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
